#!/bin/bash

#exec 1> >(logger -s -t $(basename $0)) 2>&1

if [ ! -f includes/env.cnf ]; then
  cp env.cnf.default includes/env.cnf
  nano includes/env.cnf
  [ ! -f includes/env.cnf ] && exit
  info Create includes/env.cnf
fi

source includes/env.cnf
source includes/functions.cfg
source includes/menu."$LANG"
source includes/bash_strict.sh

DEBUG=false
while getopts "h?d" opt
do
	# case statement
	case "${opt}" in
	h|\?)
		cbm_help
		# exit code
		exit 0
		;;
	d) DEBUG=true ;;
	esac
done

# Le script
#CURRENT_DIR=$(dirname "${0}")
#SCRIPT_NAME=$(basename "${0}")
HOSTNAME=$(hostname)
DATE_DU_JOUR=$(date)
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

[ $EUID -eq 0 ] && echo error "This script must run as normal user" && exit 1

# Verify pre requis

verif_pre_requis

[ -d "$PROJECTS_PATH" ] || create_env
# restore last project

PROJECT=$(menu --inputbox "What is your project?" 8 39 "$PROJECT_CURRENT" --title "Code Base Manager")

if [[ "$?" -eq 0 ]]; then
  if [ -d "$PROJECTS_PATH"/"$PROJECT" ]; then
    # save current project
    get_project_conf
    sed -i "s/^PROJECT_CURRENT=.*/PROJECT_CURRENT=$PROJECT/" "$RACINE/includes/env.cnf"
    info "Project: $PROJECT"
  else
    menu --title "Boite de dialogue Oui / Non" --yesno "Create new project $PROJECT ?" 10 60
    if [[ "$?" -eq 0 ]]; then
      while [[ :: ]];
      do        
        parm=$(menu --inputbox "What is your Moodle version?" 8 39 --title "Conf $PROJECT" "$MOODLE_VERSION_DEFAULT")
        [[ "$?" -eq 0 ]] || exit 1
        is_version_valid "$parm" && break
      done

      info Call create project "$PROJECT" "$parm"
      create_project "$PROJECT" "$parm"
      info Project "$PROJECT" created
    else
       echo "Cancel."
       exit 1
    fi
  fi
else
   echo "Select canceled."
   exit 1
fi

# Verify date pluglist.json
get_pluglist
get_moodle_desired_state "$PROJECT"
sortie=0

while [ $sortie = 0 ];
do
  OPTION=$(menu --title "Code Base Manager" --menu "Project : ${PROJECT}" 20 60 12 \
  "0"  "${menu[0]}" \
  "1"  "${menu[1]}" \
  "2"  "${menu[2]}" \
  "3"  "${menu[3]}" \
  "4"  "${menu[4]}" \
  "5"  "${menu[5]}" \
  "6"  "${menu[6]}" \
  "7"  "${menu[7]}" \
  "8"  "${menu[8]}" \
  "9"  "${menu[9]}")

  if [ "$?" -eq 0 ];
  then
    if   [ "$OPTION" = 0 ]; then add_plugin_cache
    elif [ "$OPTION" = 1 ]; then list_plugins_cache
    elif [ "$OPTION" = 2 ]; then edit_plugins
    elif [ "$OPTION" = 3 ]; then add_plugin_project
    elif [ "$OPTION" = 4 ]; then update_moodle && update_project
    elif [ "$OPTION" = 5 ]; then update_plugins_repo
    elif [ "$OPTION" = 6 ]; then update_codebase
    elif [ "$OPTION" = 7 ]; then release
    elif [ "$OPTION" = 8 ]; then help
    elif [ "$OPTION" = 9 ]; then sortie=1
    else
     echo "Vous avez annulé"
     sortie=1
    fi
  else
    #"Vous avez annulé... :-("
    sortie=1
  fi

  if [ "$DEBUG" = true ];
  then
    wait_keyboard
  fi
done

info Bye Bye